"""Initial migration: create user authentication and tool analysis tables

Revision ID: 366118d01ceb
Revises: 
Create Date: 2025-11-07 15:02:09.882167

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '366118d01ceb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('search_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('query', sa.String(), nullable=False),
    sa.Column('results', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_search_results_query'), 'search_results', ['query'], unique=False)
    op.create_table('tools',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('overview', sa.Text(), nullable=True),
    sa.Column('core_pain_point', sa.Text(), nullable=True),
    sa.Column('analysis_data', sa.JSON(), nullable=True),
    sa.Column('screenshot_url', sa.String(), nullable=True),
    sa.Column('favicon_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tools_url'), 'tools', ['url'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False, comment='用户名(唯一)'),
    sa.Column('phone', sa.String(length=20), nullable=False, comment='手机号(唯一身份凭证)'),
    sa.Column('phone_verified', sa.Boolean(), nullable=True, comment='手机号是否已验证'),
    sa.Column('email', sa.String(length=100), nullable=True, comment='邮箱(可选)'),
    sa.Column('email_verified', sa.Boolean(), nullable=True, comment='邮箱是否已验证'),
    sa.Column('password_hash', sa.String(length=255), nullable=True, comment='密码哈希(bcrypt)'),
    sa.Column('password_salt', sa.String(length=100), nullable=True, comment='密码盐值'),
    sa.Column('nickname', sa.String(length=50), nullable=True, comment='昵称'),
    sa.Column('avatar_url', sa.String(length=500), nullable=True, comment='头像URL'),
    sa.Column('bio', sa.Text(), nullable=True, comment='个人简介'),
    sa.Column('membership_level', sa.Enum('FREE', 'BASIC', 'PRO', 'ENTERPRISE', name='membershiplevel'), nullable=False, comment='会员等级'),
    sa.Column('membership_expire_at', sa.TIMESTAMP(), nullable=True, comment='会员到期时间'),
    sa.Column('auto_renew', sa.Boolean(), nullable=True, comment='是否自动续费'),
    sa.Column('total_analysis_count', sa.Integer(), nullable=True, comment='累计分析次数'),
    sa.Column('total_script_count', sa.Integer(), nullable=True, comment='累计生成文案数'),
    sa.Column('status', sa.Enum('ACTIVE', 'SUSPENDED', 'DELETED', name='userstatus'), nullable=False, comment='用户状态'),
    sa.Column('is_admin', sa.Boolean(), nullable=True, comment='是否是管理员'),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('last_login_at', sa.TIMESTAMP(), nullable=True, comment='最后登录时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_membership', 'users', ['membership_level', 'membership_expire_at'], unique=False)
    op.create_index('idx_user_phone', 'users', ['phone'], unique=False)
    op.create_index('idx_user_status', 'users', ['status'], unique=False)
    op.create_index('idx_user_username', 'users', ['username'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('audiences',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tool_id', sa.UUID(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('emoji', sa.String(), nullable=True),
    sa.Column('pain_points', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('solutions', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('match_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['tool_id'], ['tools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('oauth_bindings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='关联用户ID'),
    sa.Column('provider', sa.Enum('GOOGLE', 'GITHUB', name='oauthprovider'), nullable=False, comment='OAuth提供商'),
    sa.Column('provider_user_id', sa.String(length=255), nullable=False, comment='第三方平台用户ID'),
    sa.Column('provider_username', sa.String(length=100), nullable=True, comment='第三方平台用户名'),
    sa.Column('provider_email', sa.String(length=100), nullable=True, comment='第三方平台邮箱'),
    sa.Column('provider_avatar', sa.String(length=500), nullable=True, comment='第三方平台头像'),
    sa.Column('access_token', sa.Text(), nullable=True, comment='访问令牌'),
    sa.Column('refresh_token', sa.Text(), nullable=True, comment='刷新令牌'),
    sa.Column('token_expires_at', sa.TIMESTAMP(), nullable=True, comment='令牌过期时间'),
    sa.Column('raw_data', sa.JSON(), nullable=True, comment='原始OAuth返回数据'),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('last_used_at', sa.TIMESTAMP(), nullable=True, comment='最后使用时间'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_oauth_user_id', 'oauth_bindings', ['user_id'], unique=False)
    op.create_index('uk_provider_user', 'oauth_bindings', ['provider', 'provider_user_id'], unique=True)
    op.create_table('phone_change_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='用户ID'),
    sa.Column('old_phone', sa.String(length=20), nullable=False, comment='旧手机号'),
    sa.Column('new_phone', sa.String(length=20), nullable=False, comment='新手机号'),
    sa.Column('old_phone_verified', sa.Boolean(), nullable=True, comment='旧手机号验证状态'),
    sa.Column('new_phone_verified', sa.Boolean(), nullable=True, comment='新手机号验证状态'),
    sa.Column('ip_address', sa.String(length=45), nullable=True, comment='操作IP'),
    sa.Column('user_agent', sa.Text(), nullable=True, comment='用户代理'),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_phone_change_new_phone', 'phone_change_logs', ['new_phone'], unique=False)
    op.create_index('idx_phone_change_old_phone', 'phone_change_logs', ['old_phone'], unique=False)
    op.create_index('idx_phone_change_user_id', 'phone_change_logs', ['user_id'], unique=False)
    op.create_table('quota_usage',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='用户ID'),
    sa.Column('quota_type', sa.Enum('ANALYSIS', 'SCRIPT_GENERATION', 'API_CALL', 'EXPORT', name='quotatype'), nullable=False, comment='配额类型'),
    sa.Column('used_count', sa.Integer(), nullable=True, comment='使用次数'),
    sa.Column('usage_date', sa.Date(), nullable=False, comment='使用日期'),
    sa.Column('extra_data', sa.JSON(), nullable=True, comment='额外信息(如工具名称、文案风格等)'),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_quota_user_date', 'quota_usage', ['user_id', 'usage_date'], unique=False)
    op.create_index('idx_quota_user_type_date', 'quota_usage', ['user_id', 'quota_type', 'usage_date'], unique=False)
    op.create_table('subscriptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='用户ID'),
    sa.Column('plan_type', sa.Enum('FREE', 'BASIC', 'PRO', 'ENTERPRISE', name='membershiplevel'), nullable=False, comment='套餐类型'),
    sa.Column('billing_cycle', sa.Enum('MONTHLY', 'YEARLY', name='billingcycle'), nullable=False, comment='计费周期'),
    sa.Column('original_price', sa.DECIMAL(precision=10, scale=2), nullable=False, comment='原价'),
    sa.Column('paid_price', sa.DECIMAL(precision=10, scale=2), nullable=False, comment='实付价格'),
    sa.Column('discount_code', sa.String(length=50), nullable=True, comment='优惠码'),
    sa.Column('started_at', sa.TIMESTAMP(), nullable=False, comment='订阅开始时间'),
    sa.Column('expires_at', sa.TIMESTAMP(), nullable=False, comment='订阅到期时间'),
    sa.Column('status', sa.Enum('ACTIVE', 'EXPIRED', 'CANCELLED', 'REFUNDED', name='subscriptionstatus'), nullable=False, comment='订阅状态'),
    sa.Column('auto_renew', sa.Boolean(), nullable=True, comment='是否自动续费'),
    sa.Column('payment_method', sa.String(length=50), nullable=True, comment='支付方式'),
    sa.Column('transaction_id', sa.String(length=100), nullable=True, comment='交易ID'),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('cancelled_at', sa.TIMESTAMP(), nullable=True, comment='取消时间'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_subscription_expires_at', 'subscriptions', ['expires_at'], unique=False)
    op.create_index('idx_subscription_status', 'subscriptions', ['status'], unique=False)
    op.create_index('idx_subscription_user_id', 'subscriptions', ['user_id'], unique=False)
    op.create_table('scripts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tool_id', sa.UUID(), nullable=False),
    sa.Column('audience_id', sa.UUID(), nullable=False),
    sa.Column('style', sa.String(), nullable=False),
    sa.Column('platform', sa.String(), nullable=False),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('keywords', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['audience_id'], ['audiences.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tool_id'], ['tools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scripts')
    op.drop_index('idx_subscription_user_id', table_name='subscriptions')
    op.drop_index('idx_subscription_status', table_name='subscriptions')
    op.drop_index('idx_subscription_expires_at', table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index('idx_quota_user_type_date', table_name='quota_usage')
    op.drop_index('idx_quota_user_date', table_name='quota_usage')
    op.drop_table('quota_usage')
    op.drop_index('idx_phone_change_user_id', table_name='phone_change_logs')
    op.drop_index('idx_phone_change_old_phone', table_name='phone_change_logs')
    op.drop_index('idx_phone_change_new_phone', table_name='phone_change_logs')
    op.drop_table('phone_change_logs')
    op.drop_index('uk_provider_user', table_name='oauth_bindings')
    op.drop_index('idx_oauth_user_id', table_name='oauth_bindings')
    op.drop_table('oauth_bindings')
    op.drop_table('audiences')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index('idx_user_username', table_name='users')
    op.drop_index('idx_user_status', table_name='users')
    op.drop_index('idx_user_phone', table_name='users')
    op.drop_index('idx_user_membership', table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_tools_url'), table_name='tools')
    op.drop_table('tools')
    op.drop_index(op.f('ix_search_results_query'), table_name='search_results')
    op.drop_table('search_results')
    # ### end Alembic commands ###
